stages:
  - extract

variables:
  LOCATION: "eastus"

extract_aks_versions:
  stage: extract
  image: mcr.microsoft.com/azure-cli:2.64.0
  rules:
    - when: always
  script:
    - set -euo pipefail
    - |
      if ! command -v jq >/dev/null 2>&1; then
        if command -v apt-get >/dev/null 2>&1; then
          DEBIAN_FRONTEND=noninteractive apt-get update -y | cat
          DEBIAN_FRONTEND=noninteractive apt-get install -y jq | cat
        elif command -v apk >/dev/null 2>&1; then
          apk add --no-cache jq
        else
          echo "jq is required" >&2; exit 1
        fi
      fi
    - az aks get-versions --location "$LOCATION" -o json \
        | jq '{
            versions: [.orchestrators[] | select(.isPreview != true) | .orchestratorVersion],
            patterns: ([.orchestrators[] | select(.isPreview != true) | .orchestratorVersion
                        | split(".") | .[0:2] | join(".")] | unique | sort)
          }' \
        | tee aks_versions.json
  artifacts:
    when: always
    paths:
      - aks_versions.json
    expire_in: 1 week